version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongo-markus
    ports:
      - "27017:27017"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
